-- AlterTable
ALTER TABLE `items_orden` MODIFY `estado` ENUM('PENDIENTE', 'EN_PREPARACION', 'LISTA', 'ENTREGADA', 'CERRADA', 'CANCELADA', 'PAGADA', 'POR_COBRAR') NOT NULL DEFAULT 'PENDIENTE';

-- AlterTable
ALTER TABLE `ordenes` MODIFY `estado` ENUM('PENDIENTE', 'EN_PREPARACION', 'LISTA', 'ENTREGADA', 'CERRADA', 'CANCELADA', 'PAGADA', 'POR_COBRAR') NOT NULL DEFAULT 'PENDIENTE';
