[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps || npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build:prod"]

[start]
cmd = "node server.js"